development: &default
  adapter: postgresql
  database: mind-three_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: postgres
  password: 

test:
  <<: *default
  database: mind-three_test
